### ISSUE TITLE
请问这出了什么问题

### ISSUE THREAD

**Issue by f401** [lurenJBD/iSH-VNC#1]
![E21CC730-253C-4F8A-9A2C-70FF901D721E](https://user-images.githubusercontent.com/71924344/129756817-a1c048f5-514c-4945-9804-5ef9fcc9ac8b.jpeg)

**Comment by f401** [comment]
![33EFBBF1-144F-4619-A997-E7B712707062](https://user-images.githubusercontent.com/71924344/129597507-c30a6937-8619-4d7f-ae3a-2bf8100fda1f.png)

**Comment by lurenJBD** [comment]
抱歉抱歉，过了这么久才回复。
应该是Supervisor守护配置有些变化导致，现在的2.1.1版本脚本已经修复这个问题了。
貌似新版的默认源也被替换了，导致国内访问非常缓慢，如果遇到安装缓慢可以尝试选择菜单 的 4：修改相关配置 - 3：自动更换镜像源
